#!/usr/bin/env node

// ==================== ENVIRONMENT GENERATOR ====================
// Arsip Surat Digital Enterprise
// Generate secure .env file with random keys

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
});

console.log('');
console.log('╔══════════════════════════════════════════════╗');
console.log('║   ARSIP SURAT DIGITAL - ENV GENERATOR        ║');
console.log('╚══════════════════════════════════════════════╝');
console.log('');

// Generate random keys
const generateKey = (length = 64) => {
    return crypto.randomBytes(length).toString('hex');
};

const generateBase64Key = (length = 32) => {
    return crypto.randomBytes(length).toString('base64');
};

// Default GAS URL (Base64 encoded)
const defaultGASUrl = 'aHR0cHM6Ly9zY3JpcHQuZ29vZ2xlLmNvbS9tYWNyb3Mvcy9BS2Z5Y2J3YmxhdXcyOUN2OHJtcmpRSGhmWGdkbDBjc0JIbHhPM3h2WkppbXlCc1N5QTRGNWY5cUgyNUVqNVFZSXUtLU9HeTZCdwvZXhlYw==';

const questions = [
    {
        name: 'APP_NAME',
        question: 'Nama aplikasi',
        default: 'Arsip Surat Digital Enterprise',
    },
    {
        name: 'APP_URL',
        question: 'URL aplikasi',
        default: 'http://localhost:3000',
    },
    {
        name: 'APP_PORT',
        question: 'Port aplikasi',
        default: '3000',
    },
    {
        name: 'DB_CONNECTION',
        question: 'Tipe database (sqlite/mysql/pgsql)',
        default: 'sqlite',
    },
    {
        name: 'USE_GAS',
        question: 'Gunakan Google Apps Script? (y/n)',
        default: 'y',
    },
];

async function main() {
    const answers = {};
    
    for (const q of questions) {
        const answer = await new Promise((resolve) => {
            rl.question(`${q.question} [${q.default}]: `, (ans) => {
                resolve(ans || q.default);
            });
        });
        answers[q.name] = answer;
    }
    
    rl.close();
    
    // Generate .env content
    const envContent = `# Generated by Arsip Surat Digital ENV Generator
# Date: ${new Date().toISOString()}

APP_NAME="${answers.APP_NAME}"
APP_ENV=development
APP_DEBUG=true
APP_URL=${answers.APP_URL}
APP_PORT=${answers.APP_PORT}
APP_TIMEZONE=Asia/Jakarta
APP_LOCALE=id
APP_KEY=base64:${generateBase64Key(32)}

DB_CONNECTION=${answers.DB_CONNECTION}
DB_SQLITE_PATH=database.sqlite

JWT_SECRET=${generateKey(64)}
JWT_EXPIRES_IN=24h
JWT_REFRESH_EXPIRES_IN=7d

SESSION_DRIVER=jwt
SESSION_LIFETIME=120
MAX_LOGIN_ATTEMPTS=5
LOCKOUT_TIME=30
PASSWORD_MIN_LENGTH=8

STORAGE_DISK=local
MAX_FILE_SIZE=10485760
IMAGE_MAX_WIDTH=2000
IMAGE_MAX_HEIGHT=2000
IMAGE_QUALITY=80

MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_ENCRYPTION=tls
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_FROM_ADDRESS=noreply@arsipsurat.id
MAIL_FROM_NAME="Arsip Surat Digital"

CORS_ENABLED=true
CORS_ORIGINS=*
RATE_LIMIT_ENABLED=true
RATE_LIMIT_WINDOW=900000
RATE_LIMIT_MAX=100

ENCRYPTION_KEY=${generateKey(32)}

PWA_ENABLED=true

LOG_CHANNEL=daily
LOG_LEVEL=debug
LOG_DAYS=30

BACKUP_ENABLED=false
BACKUP_SCHEDULE="0 2 * * *"
BACKUP_KEEP=7

${answers.USE_GAS === 'y' ? `GAS_CONFIG_BASE64=${defaultGASUrl}` : '# GAS_CONFIG_BASE64='}

API_PER_PAGE=15
API_MAX_PER_PAGE=100
API_THROTTLE_ENABLED=true
API_THROTTLE_MAX=60
`;

    // Write .env file
    const envPath = path.join(__dirname, '..', '.env');
    
    if (fs.existsSync(envPath)) {
        const backupPath = path.join(__dirname, '..', `.env.backup.${Date.now()}`);
        fs.copyFileSync(envPath, backupPath);
        console.log(`\n📁 Existing .env backed up to .env.backup.${Date.now()}`);
    }
    
    fs.writeFileSync(envPath, envContent);
    
    console.log('\n✅ .env file generated successfully!');
    console.log('📋 Generated secure keys:');
    console.log(`   APP_KEY: base64:${generateBase64Key(32).substring(0, 20)}...`);
    console.log(`   JWT_SECRET: ${generateKey(64).substring(0, 20)}...`);
    console.log(`   ENCRYPTION_KEY: ${generateKey(32).substring(0, 20)}...`);
    
    if (answers.USE_GAS === 'y') {
        console.log('\n🔗 Google Apps Script configured (Base64 encoded)');
        console.log(`   Decode: node -e "console.log(Buffer.from('${defaultGASUrl.substring(0, 40)}...', 'base64').toString())"`);
    }
    
    console.log('\n🚀 Next steps:');
    console.log('   1. Edit .env with your custom values');
    console.log('   2. npm install');
    console.log('   3. npm run migrate');
    console.log('   4. npm run seed');
    console.log('   5. npm run dev');
}

main().catch(console.error);
